import {useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Navbar} from '../components/Layout';
import {auth,customerRegister,emailLogin,getReturnTo,googleLogin} from '../lib/auth';

export function CustomerLogin(){return <LoginPage role="customer" title="☕ Welcome Back to Monday's" subtitle="Login to manage your coffee orders"/>}
export function AdminLogin(){return <LoginPage role="admin" title="👑 Admin Login" subtitle="Monday's Management Portal"/>}
export function RiderLogin(){return <LoginPage role="rider" title="🛵 Rider Login" subtitle="Delivery Partner Portal"/>}

function LoginPage({role,title,subtitle}){
 const [identifier,setIdentifier]=useState(''); const [password,setPassword]=useState(''); const [showPassword,setShowPassword]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const navigate=useNavigate();
 const isCustomer=role==='customer';
 async function submit(){if(!identifier||!password){setMessage('Please enter your login details.');return;}setBusy(true);setMessage('');try{const user=await emailLogin(identifier,password,role);if(role==='customer')auth.saveCustomer(user);else auth.saveStaff(user);alert(`Welcome back, ${user.name || user.email}! ☕`);navigate(isCustomer?(getReturnTo()||'/'):role==='admin'?'/admin':'/rider',{replace:true});}catch(e){setMessage(e.code==='auth/invalid-credential'?'Invalid email or password.':e.message||'Login failed');}finally{setBusy(false)}}
 async function google(){setBusy(true);setMessage('');try{const user=await googleLogin();if(user.role!=='customer')throw new Error('This Google account is not a customer account.');auth.saveCustomer(user);navigate(getReturnTo()||'/',{replace:true});}catch(e){setMessage(e.message||'Google login failed');}finally{setBusy(false)}}
 return <><Navbar simple/><section className="section login-section"><div className="login-container"><h1 className="section-title">{title}</h1><p className="section-subtitle">{subtitle}</p><div className="login-box"><div className="login-icon"><i className={`fa-solid ${role==='customer'?'fa-user':role==='admin'?'fa-crown':'fa-motorcycle'}`}/></div><h2>{role==='customer'?'Customer Login':role==='admin'?'Admin Login':'Rider Login'}</h2><label>Email</label><div className="input-group"><i className="fa-solid fa-envelope input-leading-icon"/><input value={identifier} onChange={e=>setIdentifier(e.target.value)} type="email" placeholder="Enter your email" autoComplete="username"/></div><label>Password</label><div className="input-group password-group"><i className="fa-solid fa-lock input-leading-icon"/><input value={password} onChange={e=>setPassword(e.target.value)} type={showPassword?'text':'password'} placeholder="Enter your password" autoComplete="current-password" onKeyDown={e=>e.key==='Enter'&&submit()}/><button type="button" className="password-toggle" aria-label={showPassword?'Hide password':'Show password'} onClick={()=>setShowPassword(v=>!v)}><i className={`fa-solid ${showPassword?'fa-eye-slash':'fa-eye'}`}/></button></div><button disabled={busy} className="btn btn-primary login-btn" onClick={submit}>{busy?'Please wait…':'Login ☕'}</button>{isCustomer&&<><div className="login-divider"><span>OR</span></div><button disabled={busy} className="btn google-login-btn" onClick={google}><i className="fa-brands fa-google"/> Continue with Google</button><p className="register-text">Don't have an account?</p><Link className="register-link" to={`/customer/register${getReturnTo()?`?returnTo=${encodeURIComponent(getReturnTo())}`:''}`}>Create Account</Link></>}<p style={{marginTop:12,textAlign:'center',fontSize:14}}>{message}</p></div></div></section></>
}

export function CustomerRegister(){const [name,setName]=useState('');const [email,setEmail]=useState('');const [phone,setPhone]=useState('');const [password,setPassword]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const navigate=useNavigate();async function submit(){if(!name||!email||!password){setMessage('Please complete the required fields.');return;}if(password.length<6){setMessage('Password must be at least 6 characters.');return;}setBusy(true);setMessage('');try{const user=await customerRegister({name,email,phone,password});auth.saveCustomer(user);alert('Account created successfully ☕');navigate(getReturnTo()||'/',{replace:true});}catch(e){setMessage(e.code==='auth/email-already-in-use'?'An account with this email already exists.':e.message||'Registration failed');}finally{setBusy(false)}}return <><Navbar simple/><section className="section"><h1 className="section-title">☕ Create Monday's Account</h1><p className="section-subtitle">Join us and manage your coffee orders</p><div className="login-box"><h2>Customer Registration</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Full Name" autoComplete="name"/><br/><br/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email Address" type="email" autoComplete="email"/><br/><br/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone Number" autoComplete="tel"/><br/><br/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (minimum 6 characters)" type="password" autoComplete="new-password"/><br/><br/><button disabled={busy} className="btn btn-primary" onClick={submit}>{busy?'Creating…':'Create Account ☕'}</button><p style={{marginTop:15}}>{message}</p><p>Already have an account? <Link to={`/customer/login${getReturnTo()?`?returnTo=${encodeURIComponent(getReturnTo())}`:''}`}>Login here</Link></p></div></section></>}
