import {Link} from "react-router-dom";
import {Navbar,Footer} from "../components/Layout";

export default function Home(){return <><Navbar/><header className="hero"><div className="hero-overlay"/><div className="hero-content"><h1>A New Beginning, Every Monday</h1><p>Monday - a day in a week that always symbolizes a new beginning. It marks another chance to do better. Monday's Home Cafe aims to bring more sunshine and hope through our products and stories to our community.</p><div className="hero-badge"><i className="fa-solid fa-star"/>Freshly Made • Homemade • Local</div><div className="hero-buttons"><Link className="btn btn-primary" to="/customer/menu">Order Now</Link><Link className="btn btn-secondary" to="/customer/menu">Browse Menu</Link></div></div></header>
<section className="section categories-section"><h2 className="section-title">Our Menu</h2><p className="section-subtitle">Handcrafted with love, served with joy</p><div className="category-cards"><Link className="category-card" to="/customer/menu#rice"><div className="icon-box"><i className="fa-solid fa-bread-slice"/></div><h3>Rice &amp; Sandwiches</h3><span>6 items</span></Link><Link className="category-card" to="/customer/menu#specialty"><div className="icon-box"><i className="fa-solid fa-mug-hot"/></div><h3>Specialty Drinks</h3><span>2 items</span></Link><Link className="category-card" to="/customer/menu#coffee"><div className="icon-box"><i className="fa-solid fa-coffee"/></div><h3>Coffee &amp; Drinks</h3><span>5 items</span></Link></div></section>
<section className="section favorites-section"><h2 className="section-title">Customer Favorites</h2><p className="section-subtitle">Our most loved creations</p><div className="product-grid"><Product img="food5.png" name="Eggdrop Sandwich" desc="Scrambled egg, lettuce, ham, bacon, special sauce" price="155"/><Product img="food1.png" name="Brookies" desc="Chocolate brownie cookie creation" price="70"/><Product img="coffee7.jpg" name="Dalgona Latte" desc="Milk, coffee, and dalgona cream" price="155"/><Product img="coffee5.jpg" name="Milo Dinosaur" desc="Milo, milk, condensed milk" price="125"/></div><br/><Link className="btn btn-primary" to="/customer/menu">View Full Menu</Link></section>
<section className="section why-section"><h2 className="section-title">Why Choose Monday's?</h2><p className="section-subtitle">More than coffee, we create moments of happiness.</p><div className="why-grid"><Why icon="fa-mug-hot" title="Fresh Coffee">Handcrafted drinks made fresh every day using quality ingredients.</Why><Why icon="fa-heart" title="Made With Love">Homemade recipes prepared with passion and care.</Why><Why icon="fa-truck" title="Easy Delivery">Enjoy your favorite food and drinks delivered to your door.</Why></div></section>
<section className="delivery-banner"><div className="delivery-icon"><i className="fa-solid fa-bicycle"/></div><h2>We Deliver to Your Door</h2><p>Fresh pastries, hot coffee, and delicious meals delivered straight to you in Roxas, Oriental Mindoro.</p><div className="banner-buttons"><Link className="btn btn-primary" to="/customer/menu">Start Ordering ☕</Link></div></section>
<section className="section story-section"><div className="story-image"><img src="/images/background.jpg" alt="Monday's Home Cafe"/></div><div className="story-content"><h2 className="section-title left-aligned">Our Story</h2><p>We are young, self-taught home bakers who just love cooking, baking and art! It brings us joy to create something that brings joy to people. Monday's Home Cafe aims to bring more sunshine and hope through our products and stories to our community.</p></div></section><Footer/></>}
function Product({img,name,desc,price}){return <div className="product-card"><img src={`/images/${img}`} alt={name}/><div className="product-info"><h3>{name}</h3><p>{desc}</p><div className="price">₱{price}.00</div></div></div>}
function Why({icon,title,children}){return <div className="why-card"><i className={`fa-solid ${icon}`}/><h3>{title}</h3><p>{children}</p></div>}
